
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jan 06 23:30:06 GMT 2015
//----------------------------------------------------

package Example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LSQBRACKET = 3;
  public static final int LBRACE = 5;
  public static final int COLON = 7;
  public static final int NUMBER = 10;
  public static final int BOOLEAN = 9;
  public static final int NULL = 8;
  public static final int RSQBRACKET = 4;
  public static final int STRING = 11;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMMA = 2;
  public static final int RBRACE = 6;
}

